### ISSUE TITLE
Engineer building status UI issue

### ISSUE THREAD

**Issue by Butterscotchmaple** [CriticalFlaw/rayshud.Installer#42]
I noticed an issue while playing engineer after updating to the latest version. The building UI, the one that lets you keep track of the status of his buildings, was sitting all the way at the bottom of the screen, where the chatbox had been set to. _But_ when I died the whole thing moved to the very top of the screen where (not the chatbox, just the building UI), meaning that a simple switch of where the chatbox sits wouldn't help. Neither position is where the UI sat before updating. 
![Engi UI issue](https://user-images.githubusercontent.com/69615836/90093184-f219d200-dcf8-11ea-9ef3-e42bf4490092.png)
![Engi UI](https://user-images.githubusercontent.com/69615836/90093188-f3e39580-dcf8-11ea-9879-6258ae9832c4.png)
Images to show what I mean.

**Comment by CriticalFlaw** [comment]
The engineer building UI always gets slammed to the top when you die, that's just how it is. It's an issue with FlawHUD as well because the chat also stays on the top. Best thing to do would be to adjust the chat to stay below the engineer UI by default so that when it goes to the top the overlap won't happen.

**Comment by CriticalFlaw** [comment]
Closing because you can't prevent the Engineer menu from going up when respawning but it can be corrected by either inputting `hud_reloadscheme` into console or clicking on the Refresh HUD on the main menu.
