### ISSUE TITLE
Request: Crosshair size down to 5

### ISSUE THREAD

**Issue by andy013** [CriticalFlaw/rayshud.Installer#44]
Hey, just a small request. It would be cool if the installer supported crosshairs below size 10. For some of the styles 10 is still quite large. I managed to edit the clientscheme_xhairs.res file manually to get mine smaller but it would be cool if it was supported in the installer.

Thanks 👍

**Comment by CriticalFlaw** [comment]
Added crosshair sizes 4, 6 and 8 to the installer (0df912810871d65736c5edba2dd7d8616f7615ce) and rayshud (https://github.com/raysfire/rayshud/commit/3a82bce10530199ef6eb71d60d2665eff66432c8), because I like using even numbers over odd.

You can download the latest rayshud off GitHub and set the crosshair size yourself in `scripts/hudlayout.res` until version 4.3 of the installer is released.
